### ISSUE TITLE
👨‍💻👨‍💻👨‍💻

### ISSUE THREAD

**Issue by Vivaldo-Roque** [JuniorCarvalho06/my-python-projects#1]
Tkinter hein muitas GUI.

**Comment by JuniorCarvalho06** [comment]
kkk real, quem manda E-mail em 2021?


Em sex., 20 de ago. de 2021 às 14:11, Vivaldo Roque (Wython) <
***@***.***> escreveu:

**Comment by Vivaldo-Roque** [comment]
> kkk real, quem manda E-mail em 2021?

Na verdade eu estou respondendo do github mesmo, na sessão issues(problemas).

**Comment by JuniorCarvalho06** [comment]
Entendi, eai quer criar algum projecto?






Em seg., 23 de ago. de 2021 às 16:10, Vivaldo Roque (Wython) <
***@***.***> escreveu:

**Comment by Vivaldo-Roque** [comment]
> Entendi, eai quer criar algum projecto? Em seg., 23 de ago. de 2021 às 16:10, Vivaldo Roque (Wython) <

Já estou cheio de projectos meus arquivados e não arquivados que estou na luta.
